<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Starfall.Content/Starfall.Content.csproj" />
    <ProjectReference Include="../Starfall.Protocol/Starfall.Protocol.csproj" />
  </ItemGroup>
</Project>
