<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ShouldUnsetParentConfigurationAndPlatform>false</ShouldUnsetParentConfigurationAndPlatform>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Starfall.Content/Starfall.Content.csproj" />
    <ProjectReference Include="$(ChronoFallFamilyRoot)src/ChronoFall.Box3D/ChronoFall.Box3D.csproj"
                      AdditionalProperties="ShouldUnsetParentConfigurationAndPlatform=false" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Starfall.World" />
  </ItemGroup>
</Project>
