<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Starfall.World.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Starfall.Content/Starfall.Content.csproj" />
    <ProjectReference Include="../Starfall.Protocol/Starfall.Protocol.csproj" />
    <ProjectReference Include="../Starfall.Simulation/Starfall.Simulation.csproj" />
  </ItemGroup>
</Project>
